from config import SUBNET_MASK, DEFAULT_GATEWAY, PRIMARY_DNS, SECONDARY_DNS, ISOLATION_GROUP_NAME
from config import MASCARA_SUBREDE, GATEWAY_PADRAO, DNS_PRIMARIO, DNS_SECUNDARIO, NOME_GRUPO_ISOLAMENTO
